version: "3.5"

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    container_name: "postgres"
    restart: always
    volumes:
      - "pg-data:/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-docker-postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  pg-data:
